export const formStructureDum = {
  formName: "setoranTunai",
  formDisplayName: "Setoran Tunai",
  fields: [
    {
      fieldName: "caraPenyetoran",
      fieldDisplayName: "Cara Penyetoran",
      fieldType: "selection",
      isMandatory: true,
      minLength: 0,
      maxLength: 0,
      constraint: {
        acceptAlphabet: true,
        acceptNumber: false,
        formatCurrency: false,
        selectionDynamicFields: true,
        selectionFetch: false,
      },
      selections: [
        {
          selectionId: 32219,
          selection: "1",
          displayName: "Dengan Buku Tabungan",
          dynamicFields: [
            {
              name: "nomorKartu",
              value: "hide",
            },
          ],
        },
        {
          selectionId: 32222,
          selection: "4",
          displayName: "Tanpa Buku Tabungan",
          dynamicFields: [
            {
              name: "nomorKartu",
              value: "hide",
            },
          ],
        },
      ],
    },
    {
      fieldName: "nomorRekening",
      fieldDisplayName: "Nomor Rekening",
      fieldType: "text",
      isMandatory: true,
      minLength: 15,
      maxLength: 15,
      constraint: {
        acceptAlphabet: false,
        acceptNumber: true,
        formatCurrency: false,
        allowedSymbols: "",
        selectionDynamicFields: false,
        selectionFetch: false,
      },
    },
    {
      fieldName: "nomorKartu",
      fieldDisplayName: "Nomor Kartu",
      fieldType: "text",
      isMandatory: true,
      minLength: 16,
      maxLength: 16,
      constraint: {
        acceptAlphabet: false,
        acceptNumber: true,
        formatCurrency: false,
        selectionDynamicFields: true,
        selectionFetch: false,
      },
    },
    {
      fieldName: "namaPemilikRekening",
      fieldDisplayName: "Nama Penerima",
      fieldType: "text",
      isMandatory: true,
      minLength: 0,
      maxLength: 80,
      constraint: {
        acceptAlphabet: true,
        acceptNumber: false,
        formatCurrency: false,
        allowedSymbols: "",
        selectionDynamicFields: false,
        selectionFetch: false,
      },
    },
    {
      fieldName: "jumlahSetoran",
      fieldDisplayName: "Jumlah Setoran",
      fieldType: "text",
      isMandatory: true,
      minLength: 0,
      maxLength: 13,
      constraint: {
        acceptAlphabet: false,
        acceptNumber: true,
        formatCurrency: true,
        allowedSymbols: "terbilang terbilang",
        selectionDynamicFields: false,
        selectionFetch: false,
      },
    },
    {
      fieldName: "terbilang",
      fieldDisplayName: "Terbilang",
      fieldType: "terbilang",
      isMandatory: true,
      minLength: 0,
      maxLength: 0,
      constraint: {
        acceptAlphabet: true,
        acceptNumber: false,
        formatCurrency: false,
        allowedSymbols: "",
        selectionDynamicFields: false,
        selectionFetch: false,
      },
    },
    {
      fieldName: "sumberDana",
      fieldDisplayName: "Sumber Dana",
      fieldType: "text",
      isMandatory: true,
      minLength: 0,
      maxLength: 0,
      constraint: {
        acceptAlphabet: true,
        acceptNumber: false,
        formatCurrency: false,
        allowedSymbols: "",
        selectionDynamicFields: false,
        selectionFetch: false,
      },
    },
    {
      fieldName: "namaPenyetor",
      fieldDisplayName: "Nama Penyetor",
      fieldType: "text",
      isMandatory: true,
      minLength: 0,
      maxLength: 80,
      constraint: {
        acceptAlphabet: true,
        acceptNumber: false,
        formatCurrency: false,
        allowedSymbols: "",
        selectionDynamicFields: false,
        selectionFetch: false,
      },
    },
    {
      fieldName: "nomorTelepon",
      fieldDisplayName: "Nomor Handphone",
      fieldType: "text",
      isMandatory: true,
      minLength: 9,
      maxLength: 13,
      constraint: {
        acceptAlphabet: false,
        acceptNumber: true,
        formatCurrency: false,
        allowedSymbols: "",
        selectionDynamicFields: false,
        selectionFetch: false,
      },
    },
  ],
  errorCode: "1000",
  errorMssg: "Success",
};
